### ISSUE TITLE
Unknown lag from DC2

### ISSUE THREAD

**Issue by plebexer** [imDaniX/Dangerous-Caves-2#14] opened 2020-04-24 01:16 UTC
hey! i was using dangerouscaves before, and now i updated to dangerous caves2, im going to do a heapdup later today, but with 40 - 60 players for some reason dangerouscaves2 is on top of the timings and i also have some mobs, cave aging and cave-ins disabled, and before updating to dangerouscaves 2 it was not like this: https://timings.aikar.co/?id=0d18e4256e7f496d9afa39cadcf0d4de#plugins

**Comment by imDaniX** [comment] 2020-04-24 10:30
Can't find anything really related to lags from DC2. Would be better if you'll try [spark](https://www.spigotmc.org/resources/spark.57242/) tool.

**Comment by imDaniX** [comment] 2020-04-26 22:51
Someone messaged me with the same problem. I guess it's confirmed now.
Tried to fix the issue in latest commit https://github.com/imDaniX/Dangerous-Caves-2/commit/6857a801495b3a2e05b77de48878e02907294aef

**Comment by plebexer** [comment] 2020-04-29 19:15
hey, im going to take a guess here, i have a plugin called serverbooster, wich limits entities per chunk, and if a limit is reached it will prevent mobs from spawning, even if another plugin is trying to spawn one, maybe your plugin tries to tick a mob that has been removed and it creates some kind of loop or something, i dont really know much about java so im just taking a guess

**Comment by imDaniX** [comment] 2020-04-29 20:13
DC2 tries to spawn a new mob(with some chance) when server is trying to spawn vanilla mob, so, I don't think so. 
Anyway, this is not the case. The lag is coming from 4-tick(entity) scheduler, and it somehow loads chunks.
Honestly, I still can't find any major freezes coming from DC2 in your timings. Right now I'm lack of information, because there's only two of you guys who experiencing it.

Did you try latest build?

**Comment by imDaniX** [comment] 2020-05-09 12:08
Closed due to inactivity.

**Comment by imDaniX** [comment] 2020-05-10 18:07
Meh, someone messaged me about chunk loading on latest version. Still waiting for some the [spark](https://www.spigotmc.org/resources/spark.57242/) analysis.

**Comment by plebexer** [comment] 2020-05-19 10:54
Hey! I Came back, sorry i have not been active, i was changing My host provider to a dedicated server and now i'm not anymore in a shared host, i tought maybe the lag was being caused by the host, but yes it was the plugin
Recently in My new host (one of the lastest ryzen with 64gb) 
I installed your plugin again because i Saw You updated the plugin, and it had been working Nice for two days, and suddenly My tps went down to 8, only with 4 players on the server, and when i went to timings i saw this: https://timings.aikar.co/?id=ad93e7aa36514ea794c69f196c3e4d93#plugins
Dangerous caves was at the top with a count of 4000000+, i also managed to make a heap dump with spark so probably later today i Will send a download link once i'm able, what i think may be happening is that the plugin has a memory leak and it can get so Bad from one second to another, yesterday i had the plugin on the server with 50 people playing and there were no problems, and today with no reason this happened with 4 players.

**Comment by imDaniX** [comment] 2020-05-19 13:48
If you can please test latest build.

**Comment by imDaniX** [comment] 2020-05-20 23:01
Should be fixed now.

**Closed by imDaniX** 2020-05-20 23:01 UTC
Labels: lag, requires testing

**Comment by plebexer** [comment] 2020-05-20 23:36
okay, i will test it
