### ISSUE TITLE
Gravel Or Sand No Falling When Broken In Caves

### ISSUE THREAD

**Issue by rrodg12** [imDaniX/Dangerous-Caves-2#16] opened 2020-05-07 21:59 UTC
I Started Using Dangerious Caves For My Survival Server And Once I Installed It I Ran Into A Problem Where When A Player Breaks A Gravel Or Sand Blocks Ig Makes The Other Sand Or Gravel Blocks Turn To Ghost Blocks Making Possible For Duping (Havent Tested It Yet) Please If This Is Your Plugin Causing It Please Fix/Update It. Thanks You!

**Comment by rrodg12** [comment] 2020-05-07 22:14
Its Just The Spawn Region That Is Affected. Outside Of Spawn Hasnt Had A Problem

**Comment by imDaniX** [comment] 2020-05-07 22:31
I don't think that it's caused by DC. Please confirm the issue - remove DC2 from your plugins and do same actions again. If problem still persists - I will look into it.

**Comment by rrodg12** [comment] 2020-05-07 22:47
Alright I Will Do. I Got To Do Something Real Quick. Btw That Spawn Is WorldGuarded So It Might Be Conflicting With It. I Will Test When I Get Back. Thanks For Fast Response

**Comment by rrodg12** [comment] 2020-05-07 23:33
I Have Done It And Its Still Doing It. Im Quessing Its Something With WorldGuard Flags, EssentialsProtect Or EssentialsAnti-Build.

**Comment by imDaniX** [comment] 2020-05-07 23:50
So, then I will close the issue. 
About your problem - it's better to ask it on some related forum, like spigotmc or some local forum from your country.

**Closed by imDaniX** 2020-05-07 23:50 UTC
Labels: bug, requires testing
